### ISSUE TITLE
fix default mentions in tagcheck set command.

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#105]
the `mentions` parameter in the [`tagcheck set`](https://github.com/quotientbot/Quotient-Bot/blob/d48db4cda83d86739589ce50efcce2bbe9738386/src/cogs/esports/__init__.py#L241) command should be optional and its default value should be 4. Also the description of this command should be changed accordingly.

**Comment by P-Pole** [comment]
Hello!

If you'd allow me, then I would love to resolve this issue, as I see it is a high priority and low complexity (Therefore won't take much time)

**Comment by deadaf** [comment]
Hello @P-Pole , Thank you for your interest.

I am assigning this issue to you.
