### ISSUE TITLE
models need some refactoring.

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#109]
although newer models have their own files, there are still many models in https://github.com/quotientbot/Quotient-Bot/blob/main/src/models/models.py that could use a file of their own. 
I suggest we shift them into src/models/misc.

**Comment by nitheesh-daram** [comment]
Hey @deadaf ,I would like to work on this , and also noticed #110 also has similar changes !can I do them in a single PR?

**Comment by 7desports5044** [comment]
thanks alot

**Comment by nitheesh-daram** [comment]
Hey ,So am i good to go with a single PR for both #109 and #110?

**Comment by deadaf** [comment]
Hello @nitheesh-daram , thanks for your interest in contributing to Quotient.

Someone actually already made a PR addressing #110 , though it was not assigned to them. 

I am assigning #109 to you, only make changes regarding that, be sure to checkout the PR 111 that addresses #110 to know what models don't need any refactoring.

**Comment by deadaf** [comment]
I am out of station right now and the internet here is too weak, the above comment was made using the Android GitHub app, there's no option to assign an issue here, but consider this issue assigned to you.
