### ISSUE TITLE
show time in different format in scrims edit panel.

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#113]
in scrims edit panel, the timestamp is shown in discord format 'R' which apparently is a bit difficult for users to understand. 
We need to change it a bit show both.

## 1st change
shown like this:
![image](https://github.com/quotientbot/Quotient-Bot/assets/72350242/ab6b4000-3e23-415c-ac45-cf299af12ea4)

should be shown like this:
![image](https://github.com/quotientbot/Quotient-Bot/assets/72350242/7992a373-33d2-4291-9561-6181a69fcb6b)
Refer this line to know how this is done: https://github.com/quotientbot/Quotient-Bot/blob/d9a6e32daeb141cfb0ed0ea8807fc2f4b9e2477a/src/cogs/esports/views/scrims/main.py#L36 
and in bracket keep the current format.

Line that needs to be edited: https://github.com/quotientbot/Quotient-Bot/blob/d9a6e32daeb141cfb0ed0ea8807fc2f4b9e2477a/src/cogs/esports/views/scrims/_edit.py#L65

## 2nd change
line that needs to be edited: https://github.com/quotientbot/Quotient-Bot/blob/d9a6e32daeb141cfb0ed0ea8807fc2f4b9e2477a/src/cogs/esports/views/scrims/_edit.py#L75

should be shown like 
![image](https://github.com/quotientbot/Quotient-Bot/assets/72350242/7992a373-33d2-4291-9561-6181a69fcb6b)

## resources
discord timestamp styles:
![image](https://github.com/quotientbot/Quotient-Bot/assets/72350242/98bde049-0f63-4338-a31f-1fe162981c09)
docs: https://discord.com/developers/docs/reference#message-formatting-timestamp-styles

**Comment by aayyuush99** [comment]
@deadaf   Please assign this issue to me.

**Comment by deadaf** [comment]
Assigned the issue to you @aayyuush99
