### ISSUE TITLE
pstatus command shows outdated data

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#114]
https://github.com/quotientbot/Quotient-Bot/blob/d9a6e32daeb141cfb0ed0ea8807fc2f4b9e2477a/src/cogs/premium/__init__.py#L38

`pstatus` command shows a user's premium status and the server's premium status, it was used in. but some of the fields no longer have any importance. 

### For User:
- Remove `Boosts Left`.
- Remove `Boosted Servers`.
- Change `Expiry` to `Ending:`

### For Server:
- Change `Boosted By` to `Upgraded By: `
- Change `Expiry Time` to `Ending`

### In both:
Show expiry time using discord's latest timestamp feature, we already have a function that needs to be used. 
Example Usage: https://github.com/quotientbot/Quotient-Bot/blob/d9a6e32daeb141cfb0ed0ea8807fc2f4b9e2477a/src/cogs/utility/events/reminder.py#L37

Use style `d`
![image](https://github.com/quotientbot/Quotient-Bot/assets/72350242/54a1ebad-5223-40ce-9d86-d6b410bc8792)

**Comment by aayyuush99** [comment]
Hello @deadaf 

I would like to work on this issue. Can you please assign it to me?

**Comment by deadaf** [comment]
Hello @aayyuush99, happy contributing :)
