### ISSUE TITLE
export tourney data before deleting.

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#129]
this is faced by a lot of users when they delete a tournament unintentionally, we should export the data for that tourney before deleting it and send it to their logs channel.

Whenever a tourney is deleted this function is called:
https://github.com/quotientbot/Quotient-Bot/blob/66bb79ecf08bd4c0bddee9cdefdc2715941f1aca/src/models/esports/tourney.py#L238

inside the above mentioned function, the get_csv function should be called to generate a file and that file should be sent to tourney.logschan
https://github.com/quotientbot/Quotient-Bot/blob/66bb79ecf08bd4c0bddee9cdefdc2715941f1aca/src/models/esports/tourney.py#L220

**Comment by SOURHEAD** [comment]
hey @deadaf I can work on it

**Comment by arthishaxom** [comment]
This issue is solved right?

**Comment by deadaf** [comment]
@arthishaxom Nope, it is open.

**Comment by pranaysunny76** [comment]
Note the parameters
