### ISSUE TITLE
[enhancement] Add button on `author.send()`

### ISSUE THREAD

**Issue by rtk-rnjn** [quotientbot/Quotient-Bot#131]
I would like to request a feature that would allow bot to send a view when calling `commands.Context.author.send(...)`. The view would have a single button with the label "Guild Name". The button would be disabled by default.

---

This feature would be useful for users who want to know the guild name in future when looking to older messages.

---

Something like this:
![image](https://github.com/quotientbot/Quotient-Bot/assets/37435729/8771103e-3460-4c5e-8d5b-2aa959e6368a)

---

Although there are exactly 3 function call in entire codebase.

**Comment by deadaf** [comment]
this seems to be a good idea, would you like to work on this issue?

**Comment by rtk-rnjn** [comment]
Assign me... Will open PR very soon

**Comment by deadaf** [comment]
Assigned this to you!
