### ISSUE TITLE
AttributeError in deleting scrims without reg channels

### ISSUE THREAD

**Issue by deadaf** [quotientbot/Quotient-Bot#150]
https://github.com/quotientbot/Quotient-Bot/blob/5b5836198d7a0f804f4652232407ed8acb414aa7/src/models/esports/scrims.py#L482C3-L482C3

If the scrim's registration channel has been deleted, scrim.registration_channel will return None, hence throwing an `AttributeError`, in this line we want to directly reference `scrim.registration_channel_id`.

**Comment by arthishaxom** [comment]
Hello, I would like to work on this issue
Thank you.
