### ISSUE TITLE
Checks kinda not working

### ISSUE THREAD

**Issue by ritik0ranjan** [quotientbot/Quotient-Bot#26]
https://github.com/quotientbot/Quotient-Bot/blob/06216a82416f06f0208a870b1092ca2bef75b481/src/cogs/giveaway/__init__.py#L44
I think the `check` kinda not working. 

It should be something like:
```python
def check(message: discord.Message):
  if message.author == ctx.author and message.channel == ctx.channel:
    if message.content.strip().lower() == "cancel": raise GiveawayError("Alright, reverting all process.")
    return True
```

Re-create: 
User with Giveaways Role: `qgcreate`
Quotient Bot: <GW_EMBED>
Me the owner of the server: `cancel`
Quotient Bot: <CANCELED>
 
![Capture](https://user-images.githubusercontent.com/37435729/123988478-af7ee800-d9e5-11eb-89f3-426971052e3e.JPG)
![Capture2](https://user-images.githubusercontent.com/37435729/123988500-b6a5f600-d9e5-11eb-87d8-83345c1a19f0.JPG)

https://github.com/quotientbot/Quotient-Bot/blob/06216a82416f06f0208a870b1092ca2bef75b481/src/cogs/giveaway/__init__.py#L20
Also it would better, if not only `giveaways`, `giveaways manager` should be added too. Ugh. It look nicer

**Comment by ShashankKumarSaxena** [comment]
Yeah, the bot takes the cancelation from the other user except the author as you mentioned. The check should check first the flags like message author and channel and after that anything else.

**Comment by swayyed** [comment]
> Yeah, the bot takes the cancelation from the other user except the author as you mentioned. The check should check first the flags like message author and channel and after that anything else.

What are you trying to say :pain: 
hindi mai bolde bhai 😂

**Comment by deadaf** [comment]
a dumb mistake :c

**Comment by ShashankKumarSaxena** [comment]
sad
