### ISSUE TITLE
 [URGENT MESSAGE FROM SWAYY] [URGENT MESSAGE FROM SWAYY]

### ISSUE THREAD

**Issue by swayyed** [quotientbot/Quotient-Bot#72]
@deadaf pls pin this msg in announcements or general where everyone can see it. (important)

A step back, for the miles ahead.

Hi everyone.
It seems like I would never be able to return to this server as Swayy. My discord account had 2FA and recently I was travelling from Delhi to Lucknow. On my way back, I lost my backpack. It had my laptop wallet and my phone too. So, I lost my Google Authenticator, backup codes and password too (I used lastpass as password manager). Unfortunately, Discord has replied that they will not be able to remove my 2FA, thus cutting down any chances of account recovery, and I won't feel the same vibe if I create a new account and join back. Everything is just lost. I had many memories with my account, many friends and many achievements. (no badges sadge) So, the conclusion is, my account is fucked forever and I don't feel like coming back to this platform again due to numerous reasons. I will keep trying to get my account back even though I know the chances are thinner than Rohit himself. I pray nothing but a touch of understanding :pray: 

Now since I'm gone, and I can't even text in the support server, here are some honourable mentions with the people I made memories with:
@deadshot#7999: Thanks for holding my hand in python. hehe. you gave me everything, trusted me as your admin, repository write access, quo coins etc. Thanks for everything. If I will return to Discord you'd be the first person whom I'll DM. Dont forget me pls
@RAGEGOD#0009: mera beta i lob u harami hi rehna aur betichod netflix pass nhi diye tum aakhiri samay jao lodu :angry: 
@Krypton#8888 10000 rs paisa barbaad lol, fir bhi humesha polite and sexy rahe tum dhanyawaad bro. humesha credit card ki kami tumne door ki lol
@Aaru#0631 Thnx mujhse baat krne ke liye and bts frend hone ke liye lol and sorry ab mai bts ka boht bada virodhi hogya hu aur unka twitter par boht mazaak udata hu *pain*
@hrishikesh#9582 gaand hilade ek baar bhai hehe
**Wiper Chacha**: thnx valorant mai mujhse 1v1 haarne ke liye :joy: tumhara dimaag boht bada hai acchi jagah hi lagana humesha
**Ashish (lograck wala)** bye bhay :")
**Vein** Joi Nepala
**Scypher** code karo padhai mai kuch nhi rakha hai tbh
**Aman!#2484 and uska admin ym ka**: bye guys tumhe bhi nhi bhullunga kabhi :pensive: 

Honourable mentions (chutiye ke lye):
Alone: LOL bhai teri english sunke round the year entertainment hua. lekin tum chudbure ho CHUDBURE
Jash: bhangi hai yeh sabse bada fr

Guys all of you were great (except honourable wale lol), sorry if i missed someone jis time ye likhra tha jo jo online tha uske baare mai likh diya sorry agar koi dil ka kareebi choot gya ho.

I'd continue trying to come back :smiling_face_with_tear: 
Life updates:
Preboards parso se. Exams from 25th April -> 19th May. (fawks)
Flying to UK on 21st June, maybe forever. Will work on some projects, not on swayy's github. Im deleting all my accounts id rather prefer to live an anonymous life for some reasons.
If i ever make a comeback, u can recognize me either with my name Abhinav or my texting style (way too cool tbh :sunglasses: )
Bye guys love youuuuuuuuuuuuu.

__If anyone wants to still contact me for **EMERGENCY PURPOSE** please email me at sabhinav0909@gmail.com (*NO REPLY WITHIN 2 DAYS MEANS I IGNORED YOU THANKS FOR UNDERSTANDING*)__

Rohit pls pin this in general or announcements chat i'd be grateful. :pray: 
- Swayy ducky sabka daddy
sabhinav0909@gmail.com

**Comment by swayyed** [comment]
Thanks everyone. I wont forget you...  It was an awesome ride :)

**Comment by deadaf** [comment]
chicks didn't come to homie so homie going to chicks, bye-bye bro ❤️

**Comment by rtk-rnjn** [comment]
Demn, he should be using backtick `` ` `` to prevent mention... He pinged random people over github OwO

**Comment by Shadowaf** [comment]
bai-bai :heart:

**Comment by Harsh-Bot-pixel** [comment]
By ducky I shall forget you :)

**Comment by Harsh-Bot-pixel** [comment]
*bye

**Comment by Krotron** [comment]
Bye-bye :)

**Comment by Alone-ankush** [comment]
Bhai mt jaa,kyo jaa rha..bhot miss krenge hm..bhle hi sb bye bye bol rha
Lekin sbke aank me aansu bhre pde hai..mt jaa bhai.aaja ...agr jana hi tha to etna emotional message kyo kra yrrr..aaja ab

**Comment by swayyed** [comment]
> Bhai mt jaa,kyo jaa rha..bhot miss krenge hm..bhle hi sb bye bye bol rha Lekin sbke aank me aansu bhre pde hai..mt jaa bhai.aaja ...agr jana hi tha to etna emotional message kyo kra yrrr..aaja ab

👀 marr nhi rha bhai, wapas to aaunga 1-2 saal baad tum zinda rehna bas

**Comment by Harsh-Bot-pixel** [comment]
kat gaya alone ka Kekw

**Comment by Aaru-droid12** [comment]
Swayy... we'll surely miss you...and I don't wanna question any of your likes or dislikes but it's just...I don't see any reason to hate anyone....coz it should be like either you love them or you don't care. Hating is just time waste. I hope you'll consider it.

**Comment by Aaru-droid12** [comment]
> @deadaf pls pin this msg in announcements or general where everyone can see it. (important)
> 
> A step back, for the miles ahead.
> 
> Hi everyone. It seems like I would never be able to return to this server as Swayy. My discord account had 2FA and recently I was travelling from Delhi to Lucknow. On my way back, I lost my backpack. It had my laptop wallet and my phone too. So, I lost my Google Authenticator, backup codes and password too (I used lastpass as password manager). Unfortunately, Discord has replied that they will not be able to remove my 2FA, thus cutting down any chances of account recovery, and I won't feel the same vibe if I create a new account and join back. Everything is just lost. I had many memories with my account, many friends and many achievements. (no badges sadge) So, the conclusion is, my account is fucked forever and I don't feel like coming back to this platform again due to numerous reasons. I will keep trying to get my account back even though I know the chances are thinner than Rohit himself. I pray nothing but a touch of understanding 🙏
> 
> Now since I'm gone, and I can't even text in the support server, here are some honourable mentions with the people I made memories with: @deadshot#7999: Thanks for holding my hand in python. hehe. you gave me everything, trusted me as your admin, repository write access, quo coins etc. Thanks for everything. If I will return to Discord you'd be the first person whom I'll DM. Dont forget me pls @ragegod#9: mera beta i lob u harami hi rehna aur betichod netflix pass nhi diye tum aakhiri samay jao lodu 😠 @krypton#8888 10000 rs paisa barbaad lol, fir bhi humesha polite and sexy rahe tum dhanyawaad bro. humesha credit card ki kami tumne door ki lol @aaru#0631 Thnx mujhse baat krne ke liye and bts frend hone ke liye lol and sorry ab mai bts ka boht bada virodhi hogya hu aur unka twitter par boht mazaak udata hu _pain_ @hrishikesh#9582 gaand hilade ek baar bhai hehe **Wiper Chacha**: thnx valorant mai mujhse 1v1 haarne ke liye 😂 tumhara dimaag boht bada hai acchi jagah hi lagana humesha **Ashish (lograck wala)** bye bhay :") **Vein** Joi Nepala **Scypher** code karo padhai mai kuch nhi rakha hai tbh **Aman!#2484 and uska admin ym ka**: bye guys tumhe bhi nhi bhullunga kabhi 😔
> 
> Honourable mentions (chutiye ke lye): Alone: LOL bhai teri english sunke round the year entertainment hua. lekin tum chudbure ho CHUDBURE Jash: bhangi hai yeh sabse bada fr
> 
> Guys all of you were great (except honourable wale lol), sorry if i missed someone jis time ye likhra tha jo jo online tha uske baare mai likh diya sorry agar koi dil ka kareebi choot gya ho.
> 
> I'd continue trying to come back 🥲 Life updates: Preboards parso se. Exams from 25th April -> 19th May. (fawks) Flying to UK on 21st June, maybe forever. Will work on some projects, not on swayy's github. Im deleting all my accounts id rather prefer to live an anonymous life for some reasons. If i ever make a comeback, u can recognize me either with my name Abhinav or my texting style (way too cool tbh 😎 ) Bye guys love youuuuuuuuuuuuu.
> 
> **If anyone wants to still contact me for **EMERGENCY PURPOSE** please email me at [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com) (_NO REPLY WITHIN 2 DAYS MEANS I IGNORED YOU THANKS FOR UNDERSTANDING_)**
> 
> Rohit pls pin this in general or announcements chat i'd be grateful. 🙏
> 
> * Swayy ducky sabka daddy
>   [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com)

Swayy... we'll surely miss you...and I don't wanna question any of your likes or dislikes but it's just...I don't see any reason to hate anyone....coz it should be like either you love them or you don't care. Hating is just time waste. I hope you'll consider it.

**Comment by Harsh-Bot-pixel** [comment]
Mereko ab rona araha hai Ye msg pad kr 😢

**Comment by Alone-ankush** [comment]
> > @deadaf pls pin this msg in announcements or general where everyone can see it. (important)
> > A step back, for the miles ahead.
> > Hi everyone. It seems like I would never be able to return to this server as Swayy. My discord account had 2FA and recently I was travelling from Delhi to Lucknow. On my way back, I lost my backpack. It had my laptop wallet and my phone too. So, I lost my Google Authenticator, backup codes and password too (I used lastpass as password manager). Unfortunately, Discord has replied that they will not be able to remove my 2FA, thus cutting down any chances of account recovery, and I won't feel the same vibe if I create a new account and join back. Everything is just lost. I had many memories with my account, many friends and many achievements. (no badges sadge) So, the conclusion is, my account is fucked forever and I don't feel like coming back to this platform again due to numerous reasons. I will keep trying to get my account back even though I know the chances are thinner than Rohit himself. I pray nothing but a touch of understanding 🙏
> > Now since I'm gone, and I can't even text in the support server, here are some honourable mentions with the people I made memories with: @deadshot#7999: Thanks for holding my hand in python. hehe. you gave me everything, trusted me as your admin, repository write access, quo coins etc. Thanks for everything. If I will return to Discord you'd be the first person whom I'll DM. Dont forget me pls @ragegod#9: mera beta i lob u harami hi rehna aur betichod netflix pass nhi diye tum aakhiri samay jao lodu 😠 @krypton#8888 10000 rs paisa barbaad lol, fir bhi humesha polite and sexy rahe tum dhanyawaad bro. humesha credit card ki kami tumne door ki lol @aaru#0631 Thnx mujhse baat krne ke liye and bts frend hone ke liye lol and sorry ab mai bts ka boht bada virodhi hogya hu aur unka twitter par boht mazaak udata hu _pain_ @hrishikesh#9582 gaand hilade ek baar bhai hehe **Wiper Chacha**: thnx valorant mai mujhse 1v1 haarne ke liye 😂 tumhara dimaag boht bada hai acchi jagah hi lagana humesha **Ashish (lograck wala)** bye bhay :") **Vein** Joi Nepala **Scypher** code karo padhai mai kuch nhi rakha hai tbh **Aman!#2484 and uska admin ym ka**: bye guys tumhe bhi nhi bhullunga kabhi 😔
> > Honourable mentions (chutiye ke lye): Alone: LOL bhai teri english sunke round the year entertainment hua. lekin tum chudbure ho CHUDBURE Jash: bhangi hai yeh sabse bada fr
> > Guys all of you were great (except honourable wale lol), sorry if i missed someone jis time ye likhra tha jo jo online tha uske baare mai likh diya sorry agar koi dil ka kareebi choot gya ho.
> > I'd continue trying to come back 🥲 Life updates: Preboards parso se. Exams from 25th April -> 19th May. (fawks) Flying to UK on 21st June, maybe forever. Will work on some projects, not on swayy's github. Im deleting all my accounts id rather prefer to live an anonymous life for some reasons. If i ever make a comeback, u can recognize me either with my name Abhinav or my texting style (way too cool tbh 😎 ) Bye guys love youuuuuuuuuuuuu.
> > **If anyone wants to still contact me for **EMERGENCY PURPOSE** please email me at [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com) (_NO REPLY WITHIN 2 DAYS MEANS I IGNORED YOU THANKS FOR UNDERSTANDING_)**
> > Rohit pls pin this in general or announcements chat i'd be grateful. 🙏
> > 
> > * Swayy ducky sabka daddy
> >   [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com)
> 
> Swayy... we'll surely miss you...and I don't wanna question any of your likes or dislikes but it's just...I don't see any reason to hate anyone....coz it should be like either you love them or you don't care. Hating is just time waste. I hope you'll consider it. Best wishes for the future. Take care 💝

Loving is also time waste 💀

**Comment by Alone-ankush** [comment]
> > Bhai mt jaa,kyo jaa rha..bhot miss krenge hm..bhle hi sb bye bye bol rha Lekin sbke aank me aansu bhre pde hai..mt jaa bhai.aaja ...agr jana hi tha to etna emotional message kyo kra yrrr..aaja ab
> 
> 👀 marr nhi rha bhai, wapas to aaunga 1-2 saal baad tum zinda rehna bas

Bhai jaate jaate afk ka code bataate jaa re 😒

**Comment by Aaru-droid12** [comment]
> > > @deadaf pls pin this msg in announcements or general where everyone can see it. (important)
> > > A step back, for the miles ahead.
> > > Hi everyone. It seems like I would never be able to return to this server as Swayy. My discord account had 2FA and recently I was travelling from Delhi to Lucknow. On my way back, I lost my backpack. It had my laptop wallet and my phone too. So, I lost my Google Authenticator, backup codes and password too (I used lastpass as password manager). Unfortunately, Discord has replied that they will not be able to remove my 2FA, thus cutting down any chances of account recovery, and I won't feel the same vibe if I create a new account and join back. Everything is just lost. I had many memories with my account, many friends and many achievements. (no badges sadge) So, the conclusion is, my account is fucked forever and I don't feel like coming back to this platform again due to numerous reasons. I will keep trying to get my account back even though I know the chances are thinner than Rohit himself. I pray nothing but a touch of understanding 🙏
> > > Now since I'm gone, and I can't even text in the support server, here are some honourable mentions with the people I made memories with: @deadshot#7999: Thanks for holding my hand in python. hehe. you gave me everything, trusted me as your admin, repository write access, quo coins etc. Thanks for everything. If I will return to Discord you'd be the first person whom I'll DM. Dont forget me pls @ragegod#9: mera beta i lob u harami hi rehna aur betichod netflix pass nhi diye tum aakhiri samay jao lodu 😠 @krypton#8888 10000 rs paisa barbaad lol, fir bhi humesha polite and sexy rahe tum dhanyawaad bro. humesha credit card ki kami tumne door ki lol @aaru#0631 Thnx mujhse baat krne ke liye and bts frend hone ke liye lol and sorry ab mai bts ka boht bada virodhi hogya hu aur unka twitter par boht mazaak udata hu _pain_ @hrishikesh#9582 gaand hilade ek baar bhai hehe **Wiper Chacha**: thnx valorant mai mujhse 1v1 haarne ke liye 😂 tumhara dimaag boht bada hai acchi jagah hi lagana humesha **Ashish (lograck wala)** bye bhay :") **Vein** Joi Nepala **Scypher** code karo padhai mai kuch nhi rakha hai tbh **Aman!#2484 and uska admin ym ka**: bye guys tumhe bhi nhi bhullunga kabhi 😔
> > > Honourable mentions (chutiye ke lye): Alone: LOL bhai teri english sunke round the year entertainment hua. lekin tum chudbure ho CHUDBURE Jash: bhangi hai yeh sabse bada fr
> > > Guys all of you were great (except honourable wale lol), sorry if i missed someone jis time ye likhra tha jo jo online tha uske baare mai likh diya sorry agar koi dil ka kareebi choot gya ho.
> > > I'd continue trying to come back 🥲 Life updates: Preboards parso se. Exams from 25th April -> 19th May. (fawks) Flying to UK on 21st June, maybe forever. Will work on some projects, not on swayy's github. Im deleting all my accounts id rather prefer to live an anonymous life for some reasons. If i ever make a comeback, u can recognize me either with my name Abhinav or my texting style (way too cool tbh 😎 ) Bye guys love youuuuuuuuuuuuu.
> > > **If anyone wants to still contact me for **EMERGENCY PURPOSE** please email me at [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com) (_NO REPLY WITHIN 2 DAYS MEANS I IGNORED YOU THANKS FOR UNDERSTANDING_)**
> > > Rohit pls pin this in general or announcements chat i'd be grateful. 🙏
> > > 
> > > * Swayy ducky sabka daddy
> > >   [sabhinav0909@gmail.com](mailto:sabhinav0909@gmail.com)
> > 
> > 
> > Swayy... we'll surely miss you...and I don't wanna question any of your likes or dislikes but it's just...I don't see any reason to hate anyone....coz it should be like either you love them or you don't care. Hating is just time waste. I hope you'll consider it. Best wishes for the future. Take care 💝
> 
> Loving is also time waste 

ou won't get it....

> 
You won't get it....

**Comment by Harsh-Bot-pixel** [comment]
Abhi abhi yad aya agr tumhara koi  bot hai quotient ko chhodkr to mujh uska access dedo
