### ISSUE TITLE
Catch/raise errors properly

### ISSUE THREAD

**Issue by Wiper-R** [quotientbot/Quotient-Bot#85]
Not using dpy for quite while, but I think following block of code will eat all errors except `ScrimError, TourneyError, PointsError`. This all could be fixed by adding a `raise error` keyword/statement after that if block.

```py
async def cog_command_error(self, ctx, error):
        if isinstance(error, (ScrimError, TourneyError, PointsError)):
            return await ctx.error(error)
```

**Comment by rtk-rnjn** [comment]
I don't think its actually possible 
```py
data: dict = {"abc": 123}
try:
    data["abc"].append(456)  # type: ignore
except (IndexError, KeyError) as e:
    print(e)
```
As per you "`but I think following block of code will eat all errors except ...`", but it will raise other errors, which is `AttributeError` in this case
```py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
    data["abc"].append(456)  # type: ignore
AttributeError: 'int' object has no attribute 'append'
```

**Comment by Wiper-R** [comment]
> I don't think its actually possible
> 
> ```python
> data: dict = {"abc": 123}
> try:
>     data["abc"].append(456)  # type: ignore
> except (IndexError, KeyError) as e:
>     print(e)
> ```
> 
> As per you "`but I think following block of code will eat all errors except ...`", but it will raise other errors as well, which is `AttributeError` in this case
> 
> ```python
> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
>     data["abc"].append(456)  # type: ignore
> AttributeError: 'int' object has no attribute 'append'
> ```

This is totally different concept, in the mentioned snippet there is no try, except block so using `super().cog_command_error(..args)` or `raise error` is required in my opinion.

**Comment by deadaf** [comment]
actually, the whole block is useless, we don't raise ScrimError, TourneyError, PointsError anywhere in the cog. Also, it isn't required anymore because I have removed all the commands except 3 and they just send an embed with a view. 

![image](https://user-images.githubusercontent.com/72350242/171976708-42aef97c-6a40-4f90-b3c6-f2493dded2ce.png)

so the whole cog is around 20-30 lines. (kuch changes already push kr rkhe hain new scrims cog m , kuch baaki hain)

**Comment by rtk-rnjn** [comment]
@Wiper-R Its actually same. ^.^ Have a [look](https://github.com/Rapptz/discord.py/blob/6901907b692c72c4e036ee7b9a0c986bc622c998/discord/ext/commands/bot.py#L1325-L1335)

**Comment by Wiper-R** [comment]
> @Wiper-R Its actually same. ^.^ Have a [look](https://github.com/Rapptz/discord.py/blob/6901907b692c72c4e036ee7b9a0c986bc622c998/discord/ext/commands/bot.py#L1325-L1335)
> 
> In case your IDE saying it or any `pyright` `flake8` "Exception might be lost" then don't believe in his lies.

Hmm, it could be true although I guessed it by my own.
