### ISSUE TITLE
Handle errors properly.

### ISSUE THREAD

**Issue by Wiper-R** [quotientbot/Quotient-Bot#9]
We should consider handling error properly, instead of just raw try-except block.
```py
try:
    ...
except:
    ...
```

_**Why this is needed??**_
```py
message = await channel.send("Some Content!")

# We tried editing it

try:
    await message.edit(content='')
except:
    pass

```
Can see? above block will just eat all errors while the error is from our side.

**Comment by ItzJck** [comment]
> We should consider handling error properly, instead of just raw try-except block.
> 
> ```python
> try:
>     ...
> except:
>     ...
> ```

Yes we should

**Comment by ShashankKumarSaxena** [comment]
First tell me jack, what are those three dots called

**Comment by ItzJck** [comment]
which three dots?

**Comment by Wiper-R** [comment]
> which three dots?

stfu right now or else u will be blocked

**Comment by ShashankKumarSaxena** [comment]
> which three dots

bete mauj krdi

**Comment by ItzJck** [comment]
acha ye? ```py
...
```
means ki 
```python
try:
 #code will try to do something
except:
#agar code kuch nhi kr paya toh wo ye use krre ga

**Comment by Aman-14** [comment]
Yup, using bare except can cause serious issues in the program, its always a good practice to include a specific Exception.
Read : https://www.flake8rules.com/rules/E722.html#:~:text=When%20catching%20exceptions%2C%20mention%20specific,and%20can%20disguise%20other%20problems.

**Comment by sp-sketch** [comment]
nice time pass going on here

**Comment by TierGamerpy** [comment]
ye khula kyu hai pull request abhi tak :thinking:

**Comment by Wiper-R** [comment]
> ye khula kyu hai pull request abhi tak 🤔

khula hi rahega jabtk sahi nahi hoge wo errors
